apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: maven-rc
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java
  template:  #POD TEMPLATE
    metadata:
      name: maven-pod 
      labels:
        app: java
    spec:
      containers:
      - name: maven-cont
        image: 8983795200/maven-web-application:1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: java-svc-np
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - name: java-port
    port: 8080   # service port
    targetPort: 8080  # container port
    protocol: TCP
    nodePort: 30024
